# Generated by Django 3.2.3 on 2021-06-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaidCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100, verbose_name='Course Name')),
                ('photo', models.ImageField(upload_to='Course/images', verbose_name='Cover Photo')),
                ('video', models.FileField(upload_to='Course/video', verbose_name='Tittle Video')),
                ('price', models.IntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pakg', models.CharField(choices=[('basic', 'Basic'), ('standard', 'STANDARD'), ('premium', 'PREMIUM')], default='basic', max_length=8)),
                ('tittle', models.CharField(max_length=100)),
                ('foffere', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Offer')),
                ('soffere', models.CharField(blank=True, max_length=50, null=True, verbose_name='Second Offer')),
                ('toffere', models.CharField(blank=True, max_length=50, null=True, verbose_name='Third Offer')),
                ('fouoffere', models.CharField(blank=True, max_length=50, null=True, verbose_name='Four Offer')),
                ('fivoffere', models.CharField(blank=True, max_length=50, null=True, verbose_name='Five Offer')),
                ('price', models.IntegerField(default=0.0)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
