# Generated by Django 3.2.3 on 2021-06-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_rename_batch_categories_batch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='creadit',
            field=models.IntegerField(default=18, verbose_name='Creadit Hours'),
        ),
    ]
