# Generated by Django 3.2.3 on 2021-06-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_category_creadit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='creadit',
        ),
        migrations.AddField(
            model_name='course',
            name='creadit',
            field=models.IntegerField(default=4, verbose_name='Creadit Hours'),
        ),
    ]
