# Generated by Django 3.2.3 on 2021-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_alter_profile_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='select',
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=8, verbose_name='Package'),
        ),
    ]
